/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/maps/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GenerateMap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        CellKind: "void" | "floor" | "corridor" | "wall" | "door";
        GeneratedMap: {
            /** Format: uint32 */
            seed: number;
            /** Format: int32 */
            width: number;
            /** Format: int32 */
            height: number;
            cells: components["schemas"]["CellKind"][];
            rooms: components["schemas"]["Room"][];
        };
        GenerateMapRequest: {
            /** Format: uint32 */
            seed: null | number;
        };
        Room: {
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
            /** Format: int32 */
            width: number;
            /** Format: int32 */
            height: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GenerateMap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["GenerateMapRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedMap"];
                };
            };
        };
    };
}
